### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by bshkspr** [gaow/kbac#1]
Hi Gao,

I have a problem to install KBAC on Windows 7 as attached. Please let me know how to fix it.

Thanks.

Ho-Joon

[KBAC_error.txt](https://github.com/gaow/kbac/files/263656/KBAC_error.txt)

**Comment by gaow** [comment]
Hi Ho-Joon,

I'm sorry the short answer is I cannot fix it. The long version is, that if you check the source code directory the `config_*.h` files, you see `*` include Linux, Mac, and 32 bit windows, but there is no 64 bit windows. Those files were automatically generated years ago by running gsl build script on different platforms. Today I no longer have a Windows computer and it is not trivial to configure one and produce the proper `config_*.h` file for use on Windows. Sorry about that.

Gao
